#!/bin/bash
#
# Migration Script - Extract Custom Configurations
# Extracts user's custom aliases, functions, exports from existing dotfiles
# Writes them to a review file for manual migration
#

set -e

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

print_header() { echo -e "${BLUE}$1${NC}"; }
print_step() { echo -e "${CYAN}→${NC} $1"; }
print_success() { echo -e "${GREEN}✓${NC} $1"; }
print_warning() { echo -e "${YELLOW}!${NC} $1"; }

# ─── Configuration ──────────────────────────────────────────────────────────
MIGRATION_FILE="$HOME/dotfiles_migration_$(date +%Y%m%d_%H%M%S).sh"

# Files to scan for custom configurations
FILES_TO_SCAN=(
  "$HOME/.zshrc"
  "$HOME/.zshenv"
  "$HOME/.zlogin"
  "$HOME/.bash_profile"
  "$HOME/.bashrc"
  "$HOME/.profile"
)

# System environment variables to EXCLUDE from migration (auto-managed)
SYSTEM_VARS=(
  "PATH"
  "HOMEBREW_PREFIX"
  "HOMEBREW_CELLAR"
  "HOMEBREW_REPOSITORY"
  "MANPATH"
  "INFOPATH"
  "SHELL"
  "HOME"
  "USER"
  "TERM"
  "LANG"
  "LC_ALL"
  "EDITOR"
  "VISUAL"
  "GPG_TTY"
  "NVM_DIR"
  "NVM_BIN"
  "NVM_INC"
  "FZF_DEFAULT_COMMAND"
  "FZF_CTRL_T_COMMAND"
  "FZF_ALT_C_COMMAND"
  "FZF_DEFAULT_OPTS"
  "DOTFILES"
)

# ─── Header ─────────────────────────────────────────────────────────────────
clear
print_header "════════════════════════════════════════════════════════════"
print_header "  Custom Configuration Migration"
print_header "════════════════════════════════════════════════════════════"
echo ""
echo "  This script will extract your custom configurations from existing"
echo "  dotfiles and save them to a review file. You can then decide which"
echo "  settings to keep in your new dotfiles setup."
echo ""

# ─── Create Migration File ──────────────────────────────────────────────────
cat > "$MIGRATION_FILE" << 'HEADER'
#!/bin/bash
#
# Custom Configuration Migration File
# Generated by dotfiles migration script
#
# INSTRUCTIONS:
# 1. Review each section below
# 2. Copy what you want to keep to:
#    - ~/.zshenv.local (system paths, Homebrew - loaded FIRST in all shells)
#    - ~/.zshrc.local (aliases, functions, exports - interactive shells only)
#    - ~/.secrets (API keys, tokens - will be chmod 600)
# 3. Delete this file when done
#
# NOTES:
# - Use ~/.zshenv.local for system-level configs (Homebrew paths, essential env vars)
# - Use ~/.zshrc.local for interactive shell configs (aliases, functions)
# - The new dotfiles are opinionated - only copy what you truly need
# - Conflicting aliases will override dotfiles defaults (check CLAUDE.md)
#

HEADER

chmod 644 "$MIGRATION_FILE"

# ─── Track what we found ────────────────────────────────────────────────────
found_aliases=false
found_functions=false
found_exports=false
found_secrets=false
found_path_additions=false
found_system_tools=false

# ─── Extract Custom Aliases ─────────────────────────────────────────────────
print_step "Scanning for custom aliases..."

{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# Custom Aliases"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# Review and copy desired aliases to: ~/.zshrc.local"
  echo "#"
  echo ""
} >> "$MIGRATION_FILE"

for file in "${FILES_TO_SCAN[@]}"; do
  if [[ -f "$file" ]] && [[ ! -L "$file" ]]; then
    # Extract alias definitions (skip global aliases with -g)
    if grep -E "^[[:space:]]*alias [^-]" "$file" 2>/dev/null; then
      found_aliases=true
      {
        echo "# From: $file"
        grep -E "^[[:space:]]*alias [^-]" "$file" | sed 's/^/# /'
        echo ""
      } >> "$MIGRATION_FILE"
    fi
  fi
done

if [[ "$found_aliases" == false ]]; then
  echo "# No custom aliases found" >> "$MIGRATION_FILE"
fi

# ─── Extract Custom Functions ───────────────────────────────────────────────
print_step "Scanning for custom functions..."

{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# Custom Functions"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# Review and copy desired functions to: ~/.zshrc.local"
  echo "#"
  echo ""
} >> "$MIGRATION_FILE"

for file in "${FILES_TO_SCAN[@]}"; do
  if [[ -f "$file" ]] && [[ ! -L "$file" ]]; then
    # Extract function definitions (basic pattern matching)
    if grep -E "^[[:space:]]*(function [a-zA-Z_][a-zA-Z0-9_]*|[a-zA-Z_][a-zA-Z0-9_]*\(\))" "$file" 2>/dev/null; then
      found_functions=true
      {
        echo "# From: $file"
        grep -E "^[[:space:]]*(function [a-zA-Z_][a-zA-Z0-9_]*|[a-zA-Z_][a-zA-Z0-9_]*\(\))" "$file" | sed 's/^/# /'
        echo "# (Full function body not extracted - review source file)"
        echo ""
      } >> "$MIGRATION_FILE"
    fi
  fi
done

if [[ "$found_functions" == false ]]; then
  echo "# No custom functions found" >> "$MIGRATION_FILE"
fi

# ─── Extract Custom Exports ─────────────────────────────────────────────────
print_step "Scanning for custom exports..."

{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# Custom Environment Variables"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# Review and copy desired exports to: ~/.zshrc.local"
  echo "# System variables (PATH, HOMEBREW_*, etc.) are auto-detected - skip those"
  echo "#"
  echo ""
} >> "$MIGRATION_FILE"

for file in "${FILES_TO_SCAN[@]}"; do
  if [[ -f "$file" ]] && [[ ! -L "$file" ]]; then
    # Extract export statements, exclude system variables
    while IFS= read -r line; do
      # Get variable name
      var_name=$(echo "$line" | sed -E 's/^[[:space:]]*export[[:space:]]+([A-Z_][A-Z0-9_]*)=.*/\1/')

      # Check if it's a system variable
      is_system=false
      for sys_var in "${SYSTEM_VARS[@]}"; do
        if [[ "$var_name" == "$sys_var" ]]; then
          is_system=true
          break
        fi
      done

      # Add to file if not a system variable
      if [[ "$is_system" == false ]]; then
        found_exports=true
        echo "# From: $file" >> "$MIGRATION_FILE"
        echo "# $line" >> "$MIGRATION_FILE"
        echo "" >> "$MIGRATION_FILE"
      fi
    done < <(grep -E "^[[:space:]]*export [A-Z_][A-Z0-9_]*=" "$file" 2>/dev/null || true)
  fi
done

if [[ "$found_exports" == false ]]; then
  echo "# No custom exports found (system variables excluded)" >> "$MIGRATION_FILE"
fi

# ─── Extract API Keys and Secrets ───────────────────────────────────────────
print_step "Scanning for API keys and secrets..."

{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# API Keys and Secrets"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# SECURITY: Copy these to: ~/.secrets (will be chmod 600)"
  echo "# DO NOT commit these to git!"
  echo "#"
  echo ""
} >> "$MIGRATION_FILE"

# Look for common API key patterns
for file in "${FILES_TO_SCAN[@]}"; do
  if [[ -f "$file" ]] && [[ ! -L "$file" ]]; then
    if grep -E "export.*(API_KEY|TOKEN|SECRET|PASSWORD|ANTHROPIC|OPENAI|GITHUB_TOKEN)" "$file" 2>/dev/null; then
      found_secrets=true
      {
        echo "# From: $file"
        grep -E "export.*(API_KEY|TOKEN|SECRET|PASSWORD|ANTHROPIC|OPENAI|GITHUB_TOKEN)" "$file" | sed 's/^/# /'
        echo ""
      } >> "$MIGRATION_FILE"
    fi
  fi
done

if [[ "$found_secrets" == false ]]; then
  echo "# No API keys or secrets found" >> "$MIGRATION_FILE"
fi

# ─── Extract Custom PATH Additions ──────────────────────────────────────────
print_step "Scanning for custom PATH additions..."

{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# Custom PATH Additions"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# Review paths below. Common ones to keep:"
  echo "#   - Custom tool installations (/opt/custom, ~/bin, etc.)"
  echo "#   - Work-specific paths"
  echo "#"
  echo "# Add to ~/.zshrc.local with:"
  echo "#   export PATH=\"/your/custom/path:\$PATH\""
  echo "#"
  echo ""
} >> "$MIGRATION_FILE"

for file in "${FILES_TO_SCAN[@]}"; do
  if [[ -f "$file" ]] && [[ ! -L "$file" ]]; then
    if grep -E "PATH=|export PATH" "$file" 2>/dev/null; then
      found_path_additions=true
      {
        echo "# From: $file"
        grep -E "PATH=|export PATH" "$file" | sed 's/^/# /'
        echo ""
      } >> "$MIGRATION_FILE"
    fi
  fi
done

if [[ "$found_path_additions" == false ]]; then
  echo "# No custom PATH additions found" >> "$MIGRATION_FILE"
fi

# ─── Detect System Tools ────────────────────────────────────────────────────
print_step "Detecting installed system tools..."

{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# Installed System Tools (Auto-Detected)"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# Most will be auto-detected by the new dotfiles - no action needed"
  echo "#"
  echo "# EXCEPTION: Custom Homebrew locations should be added to ~/.zshenv.local"
  echo "# Example:"
  echo "#   eval \"\$(\$HOME/.homebrew/bin/brew shellenv)\""
  echo "#"
  echo ""
} >> "$MIGRATION_FILE"

# Check for common version managers and tools
tools_to_check=(
  "brew:Homebrew"
  "nvm:Node Version Manager (NVM)"
  "fnm:Fast Node Manager"
  "pyenv:Python Version Manager"
  "rbenv:Ruby Version Manager"
  "rustup:Rust Toolchain Manager"
  "cargo:Rust Package Manager"
)

for tool_entry in "${tools_to_check[@]}"; do
  IFS=':' read -r cmd name <<< "$tool_entry"
  if command -v "$cmd" &>/dev/null; then
    found_system_tools=true
    location=$(command -v "$cmd")
    {
      echo "# ✓ $name"
      echo "#   Location: $location"
    } >> "$MIGRATION_FILE"

    # Special handling for Homebrew
    if [[ "$cmd" == "brew" ]]; then
      prefix=$(brew --prefix 2>/dev/null || echo "unknown")
      echo "#   Prefix: $prefix" >> "$MIGRATION_FILE"

      # Check if it's a custom location
      if [[ "$prefix" != "/opt/homebrew" ]] && [[ "$prefix" != "/usr/local" ]]; then
        {
          echo "#"
          echo "#   ⚠️  CUSTOM LOCATION DETECTED"
          echo "#"
          echo "#   Add this to ~/.zshenv.local (create if missing):"
          echo "#   "
          echo "#   if [[ -f \"$prefix/bin/brew\" ]]; then"
          echo "#     eval \"\$($prefix/bin/brew shellenv)\""
          echo "#   fi"
          echo "#"
          echo "#   Then reload: exec zsh"
        } >> "$MIGRATION_FILE"
      fi
    fi

    echo "" >> "$MIGRATION_FILE"
  fi
done

if [[ "$found_system_tools" == false ]]; then
  echo "# No system tools detected" >> "$MIGRATION_FILE"
fi

# ─── Summary ────────────────────────────────────────────────────────────────
{
  echo ""
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "# Migration Summary"
  echo "# ═══════════════════════════════════════════════════════════════════════"
  echo "#"
  echo "# What was found:"
  echo "#   - Custom aliases: $found_aliases"
  echo "#   - Custom functions: $found_functions"
  echo "#   - Custom exports: $found_exports"
  echo "#   - API keys/secrets: $found_secrets"
  echo "#   - PATH additions: $found_path_additions"
  echo "#   - System tools: $found_system_tools"
  echo "#"
  echo "# Next steps:"
  echo "#   1. Review this file carefully"
  echo "#   2. Copy wanted configs to ~/.zshrc.local"
  echo "#   3. Copy secrets to ~/.secrets (chmod 600)"
  echo "#   4. Delete this file when done"
  echo "#"
} >> "$MIGRATION_FILE"

# ─── Complete ───────────────────────────────────────────────────────────────
echo ""
print_success "Migration file created: $MIGRATION_FILE"
echo ""
echo "  Found configurations:"
echo "    • Custom aliases:      $found_aliases"
echo "    • Custom functions:    $found_functions"
echo "    • Custom exports:      $found_exports"
echo "    • API keys/secrets:    $found_secrets"
echo "    • PATH additions:      $found_path_additions"
echo "    • System tools:        $found_system_tools"
echo ""
echo "  Next steps:"
echo "    1. Review: cat $MIGRATION_FILE"
echo "    2. Copy wanted configs to: ~/.zshrc.local"
echo "    3. Copy secrets to: ~/.secrets (chmod 600)"
echo ""
